# Generated by Django 4.1.3 on 2024-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
